#!/usr/bin/env python

import sys
sys.path.append('./src')

# Bash colors for output
from colors import Color
# Plugin handling
from plugin import Manager as Plugin_Manager
from config import * 

NAME = 'madmin'
PROMPT = Color.BLUE + '[' + Color.WHITE + NAME + Color.BLUE + '] ' + Color.WHITE
EXIT = ['exit', 'quit', 'q']

plugins = Plugin_Manager()

def parse(line):

    if line.strip() == '':
        return 1

    line = line.split()

    if line[0] in EXIT:
        return(0)

    data = dict()

    data['destination'] = line[0].strip()
    if len(line) > 1:
        data['cmd'] = line[1].strip()
    else:
        data['cmd'] = None
    if len(line) > 2:
        data['args'] = line[2:]
    else:
        data['args'] = None

    if data['destination'] == 'reload':
        plugins.reload()
    elif data['destination'] == 'config':
        print(eval(data['cmd']))
    else:
        plugins.parse(data) 

    return 1
    

while parse(input(PROMPT)): pass
