#!/usr/bin/env python

import sys
sys.path.append('./src')

from os import linesep

# Plugin handling
from plugin import Manager as Plugin_Manager
# Application configuration
from config import * 
# meh
from _getch import _Getch 

plugins = Plugin_Manager()

def parse(line):

    if line.strip() == '':
        return 1

    line = line.split()

    if line[0] in EXIT:
        return(0)

    data = dict()

    data['destination'] = line[0].strip()
    if len(line) > 1:
        data['cmd'] = line[1].strip()
    else:
        data['cmd'] = None
    if len(line) > 2:
        data['args'] = line[2:]
    else:
        data['args'] = None

    if data['destination'] == 'reload':
        plugins.reload()
    elif data['destination'] == 'config':
        print(eval(data['cmd']))
    elif data['destination'] == '?':
        plugins.listPlugins()
    else:
        if not plugins.parse(data):
            print()

    return 1
    
getch = _Getch()
buff = ''
RUNNING = 1

print(PROMPT, end='')
sys.stdout.flush()
# Main loop
while RUNNING:
    ch = getch()
    # If user pressed enter, validate stuff
    if ch == '\r':
        RUNNING = parse(buff)
        buff = ''
        print(PROMPT, end='')
        sys.stdout.flush()
    else:
        sys.stdout.write(ch)
        sys.stdout.flush()

        buff += ch
